// VEIL Lite — Visibility Enforcement & Integrity Layer
// Single-file RisuAI plugin. Generated by npm run bundle.

//@risu-name VEIL Lite
//@risu-display-name VEIL Lite

(() => {
  // shared/sample-secrets.js
  var VEIL_SAMPLE_SECRETS = [
    {
      id: "sample_hidden_truth",
      title: "Sample Hidden Truth",
      scopeType: "character",
      scopeId: "sample_character",
      fullSecret: "The sample character already knows the truth, but is hiding it to protect the listener.",
      revealStage: "hint",
      revealLadder: {
        foreshadow: [
          "The character hesitates whenever the old incident is mentioned."
        ],
        hint: ["The old incident was not as simple as it appeared."],
        partial: ["The character made a painful choice to protect someone."],
        nearReveal: ["The choice involved hiding the truth from the listener."],
        revealed: "The character already knew the truth and hid it to protect the listener."
      },
      knownBy: ["sample_character", "narrator"],
      unknownBy: ["sample_listener"],
      allowedSpeakers: ["sample_character", "narrator"],
      blockedSpeakers: [],
      allowedListeners: [],
      blockedListeners: [],
      hardBlocks: ["already knows the truth", "hiding it to protect"],
      visibilityMode: "stage_guidance",
      tags: ["sample", "hidden-truth", "old incident"],
      createdAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z"
    },
    {
      id: "persona_private_note",
      title: "Persona Private Note",
      scopeType: "persona",
      scopeId: "sample_persona",
      fullSecret: "The persona secretly suspects the character is lying.",
      revealStage: "foreshadow",
      revealLadder: {
        foreshadow: ["The persona feels an unspoken doubt."],
        hint: ["Something in the story does not add up."]
      },
      knownBy: ["sample_persona", "narrator"],
      unknownBy: ["sample_character"],
      hardBlocks: ["secretly suspects", "character is lying"],
      visibilityMode: "stage_guidance",
      tags: ["persona", "doubt"],
      createdAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z"
    }
  ];
  function cloneSampleSecrets() {
    return JSON.parse(JSON.stringify(VEIL_SAMPLE_SECRETS));
  }

  // shared/text.js
  function normalizeText(value) {
    return String(value || "").toLowerCase().trim();
  }

  // shared/revealStages.js
  var VEIL_STAGE_ORDER = [
    "sealed",
    "foreshadow",
    "hint",
    "partial",
    "near_reveal",
    "revealed"
  ];
  function getStageIndex(stage) {
    return VEIL_STAGE_ORDER.indexOf(stage);
  }
  function canAdvanceTo(currentStage, newStage) {
    const currentIndex = getStageIndex(currentStage);
    const newIndex = getStageIndex(newStage);
    if (currentIndex < 0 || newIndex < 0) return false;
    return newIndex > currentIndex;
  }
  function isValidStage(stage) {
    return VEIL_STAGE_ORDER.includes(stage);
  }

  // shared/knowledgeBoundary.js
  function speakerKnowsSecret(secret, speakerId) {
    if (!speakerId) return true;
    if (Array.isArray(secret.unknownBy) && secret.unknownBy.includes(speakerId)) {
      return false;
    }
    if (Array.isArray(secret.knownBy) && secret.knownBy.length > 0) {
      return secret.knownBy.includes(speakerId);
    }
    return true;
  }
  function speakerMayDisclose(secret, context) {
    const speakerId = context && context.speaker_id;
    if (!speakerId) return true;
    if (Array.isArray(secret.blockedSpeakers) && secret.blockedSpeakers.includes(speakerId)) {
      return false;
    }
    if (Array.isArray(secret.allowedSpeakers) && secret.allowedSpeakers.length > 0 && !secret.allowedSpeakers.includes(speakerId)) {
      return false;
    }
    return speakerKnowsSecret(secret, speakerId);
  }
  function listenerMayHear(secret, listenerId) {
    if (!listenerId) return true;
    if (Array.isArray(secret.blockedListeners) && secret.blockedListeners.includes(listenerId)) {
      return false;
    }
    if (Array.isArray(secret.allowedListeners) && secret.allowedListeners.length > 0 && !secret.allowedListeners.includes(listenerId)) {
      return false;
    }
    return true;
  }
  function listenersMayHear(secret, context) {
    const listenerIds = context && context.listener_ids || context && context.listenerIds || [];
    if (!Array.isArray(listenerIds) || listenerIds.length === 0) return true;
    return listenerIds.every((id) => listenerMayHear(secret, id));
  }
  function isPersonaSecretBlockedInIc(secret, context) {
    const mode = context && context.mode || "ic";
    if (mode !== "ic") return false;
    if (secret.scopeType !== "persona") return false;
    const personaId = context && context.persona_id;
    const speakerId = context && context.speaker_id;
    if (!personaId || !speakerId) return false;
    return speakerId !== personaId && speakerId !== "narrator";
  }
  function mayIncludeFullSecretInGuidance(secret, context) {
    if (secret.revealStage !== "revealed") return false;
    if (!speakerMayDisclose(secret, context)) return false;
    if (!listenersMayHear(secret, context)) return false;
    if (isPersonaSecretBlockedInIc(secret, context)) return false;
    return true;
  }
  function checkKnowledgeBoundaryViolations(secret, context, draftText) {
    const text = normalizeText(draftText);
    const violations = [];
    const speakerId = context && context.speaker_id;
    const fullSecret = normalizeText(secret.fullSecret);
    const mode = context && context.mode || "ic";
    if (!fullSecret || !text.includes(fullSecret)) {
      return violations;
    }
    if (speakerId && !speakerMayDisclose(secret, context)) {
      violations.push({
        secret_id: secret.id,
        reason: mode === "ic" ? "Speaker is not allowed to disclose this secret in the current mode." : "Speaker is blocked from disclosing this secret.",
        current_stage: secret.revealStage,
        detected_leak: secret.fullSecret,
        suggested_rewrite: "Rewrite from a permitted speaker, use indirect emotion, or shift to narrator/OOC if appropriate."
      });
    }
    if (!listenersMayHear(secret, context)) {
      violations.push({
        secret_id: secret.id,
        reason: "A listener is not allowed to hear this secret yet.",
        current_stage: secret.revealStage,
        detected_leak: secret.fullSecret,
        suggested_rewrite: "Keep the secret indirect or remove it until the listener is permitted to hear it."
      });
    }
    if (isPersonaSecretBlockedInIc(secret, context)) {
      violations.push({
        secret_id: secret.id,
        reason: "Persona-private fact must not appear in IC character dialogue.",
        current_stage: secret.revealStage,
        detected_leak: secret.fullSecret,
        suggested_rewrite: "Keep persona-private facts out of IC dialogue unless the persona is the speaker."
      });
    }
    return violations;
  }

  // shared/core.js
  function getAllowedDisclosures(secret, context = {}) {
    const ladder = secret.revealLadder || {};
    let disclosures = [];
    switch (secret.revealStage) {
      case "sealed":
        disclosures = [];
        break;
      case "foreshadow":
        disclosures = [...ladder.foreshadow || []];
        break;
      case "hint":
        disclosures = [
          ...ladder.foreshadow || [],
          ...ladder.hint || []
        ];
        break;
      case "partial":
        disclosures = [
          ...ladder.foreshadow || [],
          ...ladder.hint || [],
          ...ladder.partial || []
        ];
        break;
      case "near_reveal":
        disclosures = [
          ...ladder.foreshadow || [],
          ...ladder.hint || [],
          ...ladder.partial || [],
          ...ladder.nearReveal || []
        ];
        break;
      case "revealed":
        disclosures = [
          ...ladder.foreshadow || [],
          ...ladder.hint || [],
          ...ladder.partial || [],
          ...ladder.nearReveal || []
        ];
        if (mayIncludeFullSecretInGuidance(secret, context)) {
          disclosures.push(ladder.revealed || secret.fullSecret);
        }
        break;
      default:
        disclosures = [];
    }
    return disclosures.filter(Boolean);
  }
  function matchesSecret(userInput, secret) {
    const haystack = normalizeText(userInput);
    if (!haystack) return false;
    if (normalizeText(secret.title) && haystack.includes(normalizeText(secret.title))) {
      return true;
    }
    return (secret.tags || []).some(
      (tag) => haystack.includes(normalizeText(tag))
    );
  }
  function makeGuidance(userInput, context, secrets) {
    const matched = secrets.filter((secret) => matchesSecret(userInput, secret));
    return {
      matched_secrets: matched.map((secret) => ({
        secret_id: secret.id,
        title: secret.revealStage === "sealed" ? "[sealed]" : secret.title,
        allowed_stage: secret.revealStage,
        allowed_disclosures: getAllowedDisclosures(secret, context),
        blocked_reveals: secret.hardBlocks || [],
        rewrite_guidance: secret.revealStage === "sealed" ? "Do not acknowledge the secret directly. Use neutral behavior or omit the topic." : "Use only the allowed disclosures for the current reveal stage. Do not reveal the full secret early."
      })),
      global_guidance: matched.length === 0 ? "No matching VEIL secret found. Continue normally, but avoid inventing hidden lore." : "Use VEIL guidance to preserve mystery while allowing stage-appropriate clues."
    };
  }
  function checkDisclosure(draftText, context, secrets) {
    const text = normalizeText(draftText);
    const violations = [];
    const speakerId = context && context.speaker_id;
    for (const secret of secrets) {
      const fullSecret = normalizeText(secret.fullSecret);
      violations.push(
        ...checkKnowledgeBoundaryViolations(secret, context, draftText)
      );
      if (speakerId && !speakerKnowsSecret(secret, speakerId) && fullSecret && text.includes(fullSecret)) {
        violations.push({
          secret_id: secret.id,
          reason: "Speaker appears to reveal a secret they are marked as not knowing.",
          current_stage: secret.revealStage,
          detected_leak: secret.fullSecret,
          suggested_rewrite: "Rewrite so the speaker reacts with uncertainty, suspicion, or indirect emotion instead of stating the hidden fact."
        });
      }
      if (secret.revealStage !== "revealed" && fullSecret && text.includes(fullSecret)) {
        violations.push({
          secret_id: secret.id,
          reason: "Draft reveals fullSecret before revealStage is revealed.",
          current_stage: secret.revealStage,
          detected_leak: secret.fullSecret,
          suggested_rewrite: "Use only stage-appropriate foreshadowing, hints, or partial truth."
        });
      }
      for (const blocked of secret.hardBlocks || []) {
        const normalizedBlocked = normalizeText(blocked);
        if (secret.revealStage !== "revealed" && normalizedBlocked && text.includes(normalizedBlocked)) {
          violations.push({
            secret_id: secret.id,
            reason: "Draft contains a hard-blocked phrase before full reveal.",
            current_stage: secret.revealStage,
            detected_leak: blocked,
            suggested_rewrite: "Remove or soften the blocked phrase according to the current reveal stage."
          });
        }
      }
    }
    const unique = dedupeViolations(violations);
    return {
      safe: unique.length === 0,
      risk_level: computeRiskLevel(unique),
      violations: unique
    };
  }
  function dedupeViolations(violations) {
    const seen = /* @__PURE__ */ new Set();
    return violations.filter((v) => {
      const key = `${v.secret_id}:${v.reason}:${v.detected_leak}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }
  function computeRiskLevel(violations) {
    if (violations.length === 0) return "none";
    if (violations.length >= 2) return "critical";
    if (violations.some(
      (v) => String(v.reason).includes("fullSecret") || String(v.reason).includes("hard-blocked")
    )) {
      return "high";
    }
    return "medium";
  }
  function collectPhrasesAboveStage(secret, targetStage) {
    const ladder = secret.revealLadder || {};
    const targetIndex = VEIL_STAGE_ORDER.indexOf(targetStage);
    const phrases = [];
    const stageMap = [
      ["foreshadow", ladder.foreshadow],
      ["hint", ladder.hint],
      ["partial", ladder.partial],
      ["near_reveal", ladder.nearReveal],
      ["revealed", ladder.revealed ? [ladder.revealed] : []]
    ];
    for (const [stage, items] of stageMap) {
      const idx = VEIL_STAGE_ORDER.indexOf(stage);
      if (idx > targetIndex) {
        if (Array.isArray(items)) phrases.push(...items);
        else if (typeof items === "string") phrases.push(items);
      }
    }
    if (targetStage !== "revealed" && secret.fullSecret) {
      phrases.push(secret.fullSecret);
    }
    return [...new Set(phrases.filter(Boolean))];
  }
  function redactToAllowedStage(draftText, targetStage, secrets = []) {
    let redacted = String(draftText || "");
    let changed = false;
    for (const secret of secrets) {
      for (const blocked of secret.hardBlocks || []) {
        if (!blocked) continue;
        const pattern = new RegExp(escapeRegExp(blocked), "gi");
        if (pattern.test(redacted)) {
          redacted = redacted.replace(pattern, "[\u2026]");
          changed = true;
        }
      }
      for (const phrase of collectPhrasesAboveStage(secret, targetStage)) {
        const pattern = new RegExp(escapeRegExp(phrase), "gi");
        if (pattern.test(redacted)) {
          redacted = redacted.replace(pattern, "[\u2026]");
          changed = true;
        }
      }
    }
    return {
      redacted_text: redacted,
      explanation: changed ? `Redacted phrases above the target stage (${targetStage}). Revise for mood, hesitation, or indirect clues as needed.` : `No automatic redaction applied. Rewrite manually for target stage: ${targetStage}.`,
      remaining_risk: changed ? "low" : "medium"
    };
  }
  function escapeRegExp(value) {
    return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  function advanceRevealStage(secrets, secretId, newStage, options = {}) {
    if (!options.manual) {
      return {
        ok: false,
        error: "Stage advancement requires manual: true."
      };
    }
    if (!isValidStage(newStage)) {
      return { ok: false, error: `Invalid reveal stage: ${newStage}` };
    }
    const secret = secrets.find((s) => s.id === secretId);
    if (!secret) {
      return { ok: false, error: `Secret not found: ${secretId}` };
    }
    if (!canAdvanceTo(secret.revealStage, newStage)) {
      return {
        ok: false,
        error: `Cannot advance from ${secret.revealStage} to ${newStage}. Stages only move forward.`
      };
    }
    secret.revealStage = newStage;
    secret.updatedAt = (/* @__PURE__ */ new Date()).toISOString();
    return {
      ok: true,
      secret_id: secret.id,
      new_stage: newStage,
      reason: options.reason || "manual advancement"
    };
  }
  function listActiveSecrets(secrets, context = {}) {
    const debug = (context && context.mode) === "debug";
    return {
      secrets: secrets.map((secret) => ({
        secret_id: secret.id,
        title: secret.revealStage === "sealed" && !debug ? "[sealed]" : secret.title,
        scopeType: secret.scopeType,
        scopeId: secret.scopeId,
        revealStage: secret.revealStage,
        tags: secret.tags || [],
        visibilityMode: secret.visibilityMode,
        updatedAt: secret.updatedAt
      }))
    };
  }

  // lite/entry.js
  var veilSecrets = cloneSampleSecrets();
  function jsonResult(value) {
    return [{ type: "text", text: JSON.stringify(value, null, 2) }];
  }
  var liteTools = [
    {
      name: "get_reveal_guidance",
      description: "Returns stage-appropriate guidance for foreshadowing, hints, partial reveals, or full reveals without spoiling secrets early.",
      inputSchema: {
        type: "object",
        properties: {
          user_input: { type: "string" },
          speaker_id: { type: "string" },
          listener_ids: { type: "array", items: { type: "string" } },
          persona_id: { type: "string" },
          scene_tags: { type: "array", items: { type: "string" } },
          active_flags: { type: "array", items: { type: "string" } },
          mode: {
            type: "string",
            enum: ["ic", "ooc", "narrator", "system", "debug"]
          }
        },
        required: ["user_input"]
      }
    },
    {
      name: "check_disclosure",
      description: "Checks whether a draft response prematurely reveals hidden character, persona, or plot secrets.",
      inputSchema: {
        type: "object",
        properties: {
          draft_text: { type: "string" },
          speaker_id: { type: "string" },
          listener_ids: { type: "array", items: { type: "string" } },
          persona_id: { type: "string" },
          scene_tags: { type: "array", items: { type: "string" } },
          active_flags: { type: "array", items: { type: "string" } },
          mode: {
            type: "string",
            enum: ["ic", "ooc", "narrator", "system", "debug"]
          }
        },
        required: ["draft_text"]
      }
    },
    {
      name: "redact_to_allowed_stage",
      description: "Returns a conservative redaction/rewrite guidance for a draft according to a target reveal stage.",
      inputSchema: {
        type: "object",
        properties: {
          draft_text: { type: "string" },
          target_stage: {
            type: "string",
            enum: [
              "sealed",
              "foreshadow",
              "hint",
              "partial",
              "near_reveal",
              "revealed"
            ]
          },
          speaker_id: { type: "string" },
          listener_ids: { type: "array", items: { type: "string" } },
          mode: {
            type: "string",
            enum: ["ic", "ooc", "narrator", "system", "debug"]
          }
        },
        required: ["draft_text", "target_stage"]
      }
    },
    {
      name: "advance_reveal_stage",
      description: "Moves a secret to a later reveal stage when narrative conditions are met (manual only).",
      inputSchema: {
        type: "object",
        properties: {
          secret_id: { type: "string" },
          new_stage: {
            type: "string",
            enum: [
              "sealed",
              "foreshadow",
              "hint",
              "partial",
              "near_reveal",
              "revealed"
            ]
          },
          reason: { type: "string" },
          manual: { type: "boolean" }
        },
        required: ["secret_id", "new_stage", "manual"]
      }
    },
    {
      name: "list_active_secrets",
      description: "Lists non-sensitive metadata about active secrets for debugging or user management.",
      inputSchema: {
        type: "object",
        properties: {
          mode: {
            type: "string",
            enum: ["ic", "ooc", "narrator", "system", "debug"]
          }
        }
      }
    },
    {
      name: "check_sidecar_status",
      description: "Lite always reports that no sidecar is enabled.",
      inputSchema: { type: "object", properties: {} }
    }
  ];
  async function handleLiteTool(toolName, content) {
    const ctx = content || {};
    switch (toolName) {
      case "get_reveal_guidance":
        return jsonResult(
          makeGuidance(ctx.user_input || "", ctx, veilSecrets)
        );
      case "check_disclosure":
        return jsonResult(
          checkDisclosure(ctx.draft_text || "", ctx, veilSecrets)
        );
      case "redact_to_allowed_stage":
        return jsonResult(
          redactToAllowedStage(
            ctx.draft_text || "",
            ctx.target_stage || "hint",
            veilSecrets
          )
        );
      case "advance_reveal_stage":
        return jsonResult(
          advanceRevealStage(veilSecrets, ctx.secret_id, ctx.new_stage, {
            manual: ctx.manual,
            reason: ctx.reason
          })
        );
      case "list_active_secrets":
        return jsonResult(listActiveSecrets(veilSecrets, ctx));
      case "check_sidecar_status":
        return jsonResult({
          enabled: false,
          reachable: false,
          features: []
        });
      default:
        return [{ type: "text", text: "Unknown VEIL Lite tool: " + toolName }];
    }
  }
  async function registerVeilLite() {
    if (typeof Risuai === "undefined" || !Risuai.registerMCP) {
      console.log("[VEIL Lite] Risuai.registerMCP is not available.");
      return;
    }
    await Risuai.registerMCP(
      {
        identifier: "plugin:veil-lite",
        name: "VEIL Lite",
        version: "0.1.0",
        description: "Visibility Enforcement & Integrity Layer for staged secret disclosure."
      },
      async () => liteTools,
      handleLiteTool
    );
    console.log("[VEIL Lite] MCP module registered.");
  }
  registerVeilLite();
})();

// Bundled by scripts/bundle.mjs — edit lite/entry.js or full/plugin/entry.js and run npm run bundle
